local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/medias/img"
public_folder: "/assets/medias/img"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Titre", name: "title", widget: "string" }

      - label: "Dates"
        name: "dates"
        widget: "list"
        field: { label: "Date", name: "date", widget: "datetime" }

      - { label: "Client", name: "client", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }

      # SERVICES
      - label: "Services"
        name: "services"
        widget: "relation"
        collection: "services"
        multiple: true
        search_fields: ["name"]
        value_field: "tag"
        display_fields: ["name"]
        min: 1

      # SKILLS
      - label: "Skills"
        name: "skills"
        widget: "list"
        fields:
          - { label: "Softwares", name: "softwares", widget: "string", required: false }
          - { label: "Hardwares", name: "hardwares", widget: "string", required: false }

      - { label: "Cover", name: "cover", widget: "image" }

      - { label: "Description", name: "description", widget: "text" }

      #SECTIONS (le plus intéressant)
      - label: "Sections"
        name: "sections"
        widget: "list"
        collapsed: true
        typeKey: "kind"
        types:
          - label: "Texte"
            name: "text"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string", required: false }
              - { label: "Texte", name: "text", widget: "text" }
              - { label: "Justification", name: "justify", widget: "select", options: ["left", "right"], default: "right" }

          - label: "Image horizontale"
            name: "image_horizontal"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }

          - label: "Vidéo horizontale"
            name: "video_horizontal"
            widget: "object"
            fields:
              - { label: "Vidéo name", name: "video", widget: "string" }

          - label: "Vidéo verticale"
            name: "video_vertical"
            widget: "object"
            fields:
              - { label: "Vidéo name", name: "video", widget: "string" }
              - { label: "Justification", name: "justify", widget: "select", options: ["left", "right"], default: "right" }

          - label: "Image verticale"
            name: "image_vertical"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Justification", name: "justify", widget: "select", options: ["left", "right"], default: "right" }

          - label: "Double image verticale"
            name: "double_image_vertical"
            widget: "object"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                min: 2
                max: 2
                field: { label: "Image", name: "image", widget: "image" }

          - label: "Double vidéo verticale"
            name: "double_video_vertical"
            widget: "object"
            fields:
              - label: "Vidéos"
                name: "videos"
                widget: "list"
                min: 2
                max: 2
                field: { label: "Vidéo name", name: "video", widget: "string" }

      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/project.njk" }

  - name: "partners"
    label: "Partners"
    label_singular: "Partner"
    folder: "src/partners"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Background", name: "background", widget: "image" }

  - name: "collaborators"
    label: "Collaborators"
    label_singular: "Collaborator"
    folder: "src/collaborators"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Profile Picture", name: "profilePicture", widget: "image" }

  - name: "services"
    label: "Services"
    label_singular: "Service"
    folder: "src/services"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Tag", name: "tag", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Compétences"
        name: "skills"
        widget: "list"
        field: { label: "Compétence", name: "skill", widget: "string" }
